#!/bin/bash 
# all the (basic) good stuff of ANKI in few lines of bash
# Happy learning!
#
SELF_DIR="$( dirname "$(readlink -f "$0")" )"; cd $SELF_DIR
flashcards_csv=""
flashcards_arr=()
blacklist=()

init(){
  cat $SELF_DIR/flashcards/*.csv > /tmp/.flashcards
}

prompt(){
  index=$1; echo "" 
  read -p "p) too easy              " answer
  echo "answer=$answer"
  [[ "$answer" == "p" ]] && {
    blacklist+=($index)
    echo "blacklist=${blacklist[*]}";
  }
  read -p "flop" flop
}
    
rand(){
  i=$(</dev/urandom tr -dc 1-6 | head -c1)
  echo $((i%$1))
}

# Usage: in_array "$needle" "${haystack[@]}"
inarray(){
    [ -z "$1" ] && return 1
    if [ -n "$BASH" ]; then
        _inarray_var_needle="$1"
        shift
        for element
        do [ X"$element" != X"$_inarray_var_needle" ] || return 0; done
    fi
    return 1
}

run(){
  local i=0; while read line; do 
    flashcards_arr+=( "${line//\"/}" )
  done < /tmp/.flashcards
  for((i=0;i<${#flashcards_arr[@]};i++)); do
    inarray $i "${blacklist[@]}" && continue 
    line="${flashcards_arr[$i]}"
    question=$(( $(rand 2) + 1 ))
    [[ $question == 1 ]] && answer=2 || answer=1
    clear
    echo -e "$line\n" | cut -d, -f$question
    read -p "" foo 
    echo -e "$line\n" | cut -d, -f$answer
    prompt $i
  done
  run # recurse..learn forever :)
}

init && run
