#!/bin/bash 
# all the (basic) good stuff of ANKI in few lines of bash
# Happy learning!
#
SELF_DIR="$( dirname "$(readlink -f "$0")" )"; 
flashcards_csv=""
flashcards_arr=()
blacklist=()

init(){
  cat "$@" > /tmp/.flashcards
}

prompt(){
  index=$1; echo "" 
  read -p "p) too easy              " answer
  [[ "$answer" == "p" ]] && {
    blacklist+=($index)
    [[ -n $DEBUG ]] && echo "blacklist=${blacklist[*]}";
  }
}
    
rand(){
  i=$(</dev/urandom tr -dc 1-6 | head -c1)
  echo $((i%$1))
}

# Usage: in_array "$needle" "${haystack[@]}"
inarray(){
    [ -z "$1" ] && return 1
    if [ -n "$BASH" ]; then
        _inarray_var_needle="$1"
        shift
        for element
        do [ X"$element" != X"$_inarray_var_needle" ] || return 0; done
    fi
    return 1
}

run(){
  local i=0; while read line; do 
    flashcards_arr+=( "${line//\"/}" )
  done < /tmp/.flashcards
  i=$(rand ${#flashcards_arr[@]})
  inarray $i "${blacklist[@]}" || {
    line="${flashcards_arr[$i]}"
    question=$(( $(rand 2) + 1 ))
    [[ $question == 1 ]] && answer=2 || answer=1
    clear
    echo -e "$line\n" | cut -d, -f$question
    read -p "" foo 
    echo -e "$line\n" | cut -d, -f$answer
    prompt $i;
  }
  run # recurse..learn forever :)
}

init "$@" && run
